" System vimrc file for Gvim
"
" Maintainer: Mike Qin <laigui@gmail.com>
" Last Change: 1/3/2018


" General
set nocompatible  
set nobackup
set noswapfile
set history=1024
set clipboard+=unnamed " Vim 的默认寄存器和系统剪贴板共享
syntax enable
syntax on


" Lang & Encoding 
set fileencodings=utf-8,gbk2312,gbk,gb18030,cp936
set encoding=utf-8
"set langmenu=zh_CN
let $LANG='en_US.UTF-8'


" GUI
colorscheme molokai
autocmd InsertLeave * se nocul "用浅色高亮当前行 
autocmd InsertEnter * se cul "用浅色高亮当前行 
"set guifont=Monaco:h14 " 调整默认字体大小
set guifont=Inconsolata:h12 " 调整默认字体大小



" 制表符  
set tabstop=4  
set expandtab  
set smarttab  
set shiftwidth=4  
set softtabstop=4  

" 行控制  
set linebreak  
set textwidth=80  
set wrap  
  
" 行号和标尺  
set number  
set ruler  
set rulerformat=%15(%c%V\ %p%%%) 

" 缩进  
set autoindent  
set cindent  
set smartindent 

" 代码折叠  
"set foldmethod=syntax  
"set foldmethod=indent 

"在查找时忽略大小写  
 set ignorecase  
 set incsearch  
 set hlsearch  
  
"显示匹配的括号  
set showmatch  

" =========  
" 功能函数  
" =========  
" 获取当前目录  
func GetPWD()  
    return substitute(getcwd(), "", "", "g")  
endf 

" 命令行于状态行  
set ch=1  
set stl=\ [File]\ %F%m%r%h%y[%{&fileformat},%{&fileencoding}]\ %w\ \ [PWD]\ %r%{GetPWD()}%h\ %=\ [Line]\ %l,%c\ %=\ %P   
set ls=2 " 始终显示状态行  

" 状态栏显示目前所执行的指令  
set showcmd   
